[build]
  command = "bun run build"
  functions = "netlify/functions"
  publish = "dist/client"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/ssr"
  status = 200
  
[[headers]]
  for = "/main.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"